name: whoami

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: whoami

  build2:
    name: "Test Status"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: whoami